app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"