CoreBundle\Document\Todo:
    repositoryClass: CoreBundle\Document\Repository\TodoRepository
    fields:
        id:
            id: true
            type: int
            strategy: INCREMENT
        content:
            type: string
        complete:
            type: boolean